FROM hauptmedia/jmeter

ADD jmeter.jmx jmeter.jmx
ADD jmeter_proxied.jmx jmeter_proxied.jmx

ADD jmeter_release.jmx jmeter_release.jmx
ADD jmeter_release_proxied.jmx jmeter_release_proxied.jmx

ADD jmeter_20_threads_release.jmx jmeter_20_threads_release.jmx
ADD jmeter_20_threads_release_proxied.jmx jmeter_20_threads_release_proxied.jmx

ADD jmeter_throughput.jmx jmeter_throughput.jmx